import express from 'express';
import { z } from 'zod';
import { prisma } from '../utils/prisma';
import { AppError } from '../utils/errors';
import { authenticate, loadClientData, AuthRequest } from '../middleware/auth';
import { approvalLimiter } from '../middleware/rateLimits';
import { assertActiveAssignee, assertProjectAccess, requireInternal } from '../workflow/authorization';
import { writeAuditEvent } from '../workflow/audit';
import { synchronizeLegacyPhases } from '../workflow/gates';

const router = express.Router();
router.use(authenticate, loadClientData);
const money = z.number().int().min(0).max(2_000_000_000);

const vendorSchema = z.object({ name: z.string().trim().min(2).max(200), contactName: z.string().trim().max(200).nullable().optional(), email: z.string().email().nullable().optional(), phone: z.string().trim().max(50).nullable().optional(), category: z.string().trim().min(2).max(100), complianceStatus: z.enum(['PENDING', 'APPROVED', 'SUSPENDED', 'EXPIRED']).default('PENDING'), active: z.boolean().default(true) });
const requestSchema = z.object({ description: z.string().trim().min(3).max(500), specification: z.string().trim().min(3).max(5000), quantity: z.number().positive(), unit: z.string().trim().min(1).max(50), requiredBy: z.coerce.date(), estimatedCostCents: money.nullable().optional(), currencyCode: z.string().regex(/^[A-Z]{3}$/).default('USD'), costCode: z.string().trim().max(50).nullable().optional(), required: z.boolean().default(true), ownerId: z.string().uuid().nullable().optional(), clientVisible: z.boolean().default(false) });
const quoteSchema = z.object({ vendorId: z.string().uuid(), amountCents: money, taxCents: money.default(0), currencyCode: z.string().regex(/^[A-Z]{3}$/).default('USD'), scope: z.string().trim().min(3).max(5000), validUntil: z.coerce.date().nullable().optional(), leadTimeDays: z.number().int().min(0).max(3650).nullable().optional() });
const substitutionSchema = z.object({ proposedSpecification: z.string().trim().min(3).max(5000), reason: z.string().trim().min(10).max(5000), costImpactCents: z.number().int().min(-2_000_000_000).max(2_000_000_000).default(0), scheduleImpactDays: z.number().int().min(-3650).max(3650).default(0), currencyCode: z.string().regex(/^[A-Z]{3}$/).default('USD'), clientAuthorizationRequired: z.boolean().default(false) });

async function findRequest(req: AuthRequest, id: string) {
  const record = await prisma.procurementRequest.findUnique({ where: { id }, include: { project: true, quotes: true, purchaseOrder: { include: { deliveries: true, invoiceMatches: true } }, substitutions: true } });
  if (!record) throw new AppError('Procurement request not found.', 404, 'NOT_FOUND');
  await assertProjectAccess(req.user, record.projectId);
  if (req.user?.role === 'CLIENT' && !record.clientVisible) throw new AppError('Procurement request not found.', 404, 'NOT_FOUND');
  return record;
}

async function canAuthorize(req: AuthRequest, projectId: string) {
  if (req.user?.role === 'ADMIN') return true;
  return false;
}

async function ensureProcurementGate(projectId: string) {
  return prisma.projectGate.upsert({ where: { projectId_fromStage_toStage: { projectId, fromStage: 'PROCUREMENT', toStage: 'FIELD_EXECUTION' } }, update: {}, create: { projectId, fromStage: 'PROCUREMENT', toStage: 'FIELD_EXECUTION', organizationId: process.env.ORGANIZATION_ID || null } });
}

async function procurementBlockers(projectId: string) {
  const requests = await prisma.procurementRequest.findMany({ where: { projectId, required: true }, include: { selectedQuote: true, purchaseOrder: { include: { deliveries: true, invoiceMatches: true } }, substitutions: true } });
  const blockers: Array<{ type: string; id: string; title: string; status: string }> = [];
  if (!requests.length) {
    blockers.push({ type: 'REGISTER', id: 'procurement-requests', title: 'At least one required procurement request must be recorded before handoff', status: 'MISSING' });
  }
  for (const request of requests) {
    if (!request.selectedQuote) blockers.push({ type: 'QUOTE', id: request.id, title: `${request.description}: approved quote required`, status: request.status });
    if (!request.purchaseOrder) blockers.push({ type: 'PURCHASE_ORDER', id: request.id, title: `${request.description}: purchase order required`, status: request.status });
    else {
      const delivered = request.purchaseOrder.deliveries.filter((item) => item.inspectionStatus === 'PASSED').reduce((sum, item) => sum + item.quantityReceived, 0);
      if (delivered < request.quantity) blockers.push({ type: 'DELIVERY', id: request.id, title: `${request.description}: delivery incomplete`, status: delivered ? 'PARTIAL' : 'MISSING' });
      if (request.purchaseOrder.deliveries.some((item) => item.inspectionStatus === 'PENDING')) blockers.push({ type: 'INSPECTION', id: request.id, title: `${request.description}: delivery inspection unresolved`, status: 'PENDING' });
      if (!request.purchaseOrder.invoiceMatches.some((item) => item.status === 'MATCHED')) blockers.push({ type: 'INVOICE_MATCH', id: request.id, title: `${request.description}: three-way verification required`, status: 'MISSING' });
    }
    for (const substitution of request.substitutions) if (substitution.status !== 'APPROVED') blockers.push({ type: 'SUBSTITUTION', id: substitution.id, title: `${request.description}: substitution authorization unresolved`, status: substitution.status });
    if (request.status !== 'CLOSED') blockers.push({ type: 'REQUEST_STATUS', id: request.id, title: `${request.description}: procurement request must be formally closed`, status: request.status });
  }
  return blockers;
}

async function notifyExceptions(projectId: string) {
  const requests = await prisma.procurementRequest.findMany({ where: { projectId, requiredBy: { lt: new Date() }, status: { notIn: ['DELIVERED', 'INSPECTED', 'INVOICED', 'MATCHED', 'CLOSED', 'CANCELLED'] } }, include: { project: true } });
  for (const request of requests) {
    const recipients = request.ownerId ? [request.ownerId] : (await prisma.user.findMany({ where: { role: 'ADMIN', active: true }, select: { id: true } })).map((item) => item.id);
    for (const userId of recipients) if (!(await prisma.notification.findFirst({ where: { userId, type: 'PROCUREMENT_EXCEPTION', itemId: request.id } }))) await prisma.notification.create({ data: { userId, type: 'PROCUREMENT_EXCEPTION', message: `Procurement item is past required-by date: ${request.description}`, itemId: request.id } });
  }
}

router.get('/vendors', async (req: AuthRequest, res, next) => { try { requireInternal(req.user); const data = await prisma.vendor.findMany({ orderBy: { name: 'asc' } }); res.json({ data, pagination: { page: 1, limit: data.length, total: data.length, totalPages: 1 } }); } catch (error) { next(error); } });
router.post('/vendors', async (req: AuthRequest, res, next) => { try { requireInternal(req.user); const data = vendorSchema.parse(req.body); const vendor = await prisma.vendor.create({ data: { ...data, organizationId: process.env.ORGANIZATION_ID || null } }); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'CREATE', entityType: 'Vendor', entityId: vendor.id, requestId: (req as any).requestId, after: vendor }); res.status(201).json(vendor); } catch (error) { next(error); } });
router.put('/vendors/:id', async (req: AuthRequest, res, next) => { try { requireInternal(req.user); const before = await prisma.vendor.findUnique({ where: { id: req.params.id } }); if (!before) throw new AppError('Vendor not found.', 404, 'NOT_FOUND'); const vendor = await prisma.vendor.update({ where: { id: before.id }, data: vendorSchema.partial().parse(req.body) }); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'UPDATE', entityType: 'Vendor', entityId: vendor.id, requestId: (req as any).requestId, before, after: vendor }); res.json(vendor); } catch (error) { next(error); } });

router.get('/projects/:projectId/procurement', async (req: AuthRequest, res, next) => {
  try {
    const project = await assertProjectAccess(req.user, req.params.projectId); const clientView = req.user?.role === 'CLIENT'; if (!clientView) await notifyExceptions(project.id);
    const [requests, vendors, gate, blockers] = await Promise.all([
      prisma.procurementRequest.findMany({ where: { projectId: project.id, ...(clientView ? { clientVisible: true } : {}) }, include: { owner: { select: { id: true, name: true } }, selectedQuote: { include: { vendor: true } }, quotes: clientView ? false : { include: { vendor: true }, orderBy: { totalCents: 'asc' } }, purchaseOrder: { include: { vendor: true, deliveries: true, invoiceMatches: true } }, substitutions: { orderBy: { createdAt: 'desc' } } }, orderBy: [{ requiredBy: 'asc' }, { createdAt: 'desc' }] }),
      clientView ? Promise.resolve([]) : prisma.vendor.findMany({ where: { active: true }, orderBy: { name: 'asc' } }),
      ensureProcurementGate(project.id), procurementBlockers(project.id),
    ]);
    res.json({ project: { id: project.id, clientId: project.clientId, currentLifecycleStage: project.currentLifecycleStage, status: project.status }, client: { id: project.client.id, name: project.client.name }, requests, vendors, gate: clientView ? null : gate, blockers: clientView ? [] : blockers });
  } catch (error) { next(error); }
});

router.post('/projects/:projectId/procurement/requests', async (req: AuthRequest, res, next) => { try { requireInternal(req.user); await assertProjectAccess(req.user, req.params.projectId); const data = requestSchema.parse(req.body); await assertActiveAssignee(data.ownerId, 'Procurement owner'); const record = await prisma.procurementRequest.create({ data: { ...data, projectId: req.params.projectId, organizationId: process.env.ORGANIZATION_ID || null } }); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'CREATE', entityType: 'ProcurementRequest', entityId: record.id, requestId: (req as any).requestId, after: record }); res.status(201).json(record); } catch (error) { next(error); } });

router.post('/procurement/requests/:id/quotes', async (req: AuthRequest, res, next) => {
  try { requireInternal(req.user); const request = await findRequest(req, req.params.id); const data = quoteSchema.parse(req.body); if (data.currencyCode !== request.currencyCode) throw new AppError('Quote currency must match the procurement request currency.', 400, 'VALIDATION_ERROR'); const vendor = await prisma.vendor.findFirst({ where: { id: data.vendorId, active: true, complianceStatus: 'APPROVED' } }); if (!vendor) throw new AppError('An active, approved vendor is required.', 400, 'VALIDATION_ERROR'); const quote = await prisma.quote.create({ data: { ...data, totalCents: data.amountCents + data.taxCents, procurementRequestId: request.id } }); await prisma.procurementRequest.update({ where: { id: request.id }, data: { status: 'QUOTING' } }); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'CREATE', entityType: 'Quote', entityId: quote.id, requestId: (req as any).requestId, after: quote }); res.status(201).json(quote); } catch (error) { next(error); }
});

router.post('/procurement/requests/:id/select-quote', approvalLimiter, async (req: AuthRequest, res, next) => {
  try { requireInternal(req.user); const request = await findRequest(req, req.params.id); if (!(await canAuthorize(req, request.projectId))) throw new AppError('Procurement authorization is required.', 403, 'FORBIDDEN'); const { quoteId } = z.object({ quoteId: z.string().uuid() }).parse(req.body); const quote = request.quotes.find((item) => item.id === quoteId); if (!quote) throw new AppError('Quote does not belong to this request.', 400, 'VALIDATION_ERROR'); if (quote.validUntil && quote.validUntil < new Date()) throw new AppError('The selected quote has expired.', 409, 'INVALID_TRANSITION'); await prisma.$transaction([prisma.quote.updateMany({ where: { procurementRequestId: request.id }, data: { status: 'NOT_SELECTED' } }), prisma.quote.update({ where: { id: quote.id }, data: { status: 'SELECTED', selectedBy: req.user!.id, selectedAt: new Date() } }), prisma.procurementRequest.update({ where: { id: request.id }, data: { selectedQuoteId: quote.id, status: 'QUOTE_SELECTED' } })]); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'APPROVE', entityType: 'Quote', entityId: quote.id, requestId: (req as any).requestId, after: { selected: true, requestId: request.id } }); res.json(await prisma.procurementRequest.findUnique({ where: { id: request.id }, include: { selectedQuote: true } })); } catch (error) { next(error); }
});

router.post('/procurement/requests/:id/purchase-order', approvalLimiter, async (req: AuthRequest, res, next) => {
  try { requireInternal(req.user); const request = await findRequest(req, req.params.id); if (!(await canAuthorize(req, request.projectId))) throw new AppError('Purchase authorization is required.', 403, 'FORBIDDEN'); if (request.purchaseOrder) throw new AppError('A purchase order already exists for this request.', 409, 'CONFLICT'); const quote = request.quotes.find((item) => item.id === request.selectedQuoteId); if (!quote) throw new AppError('An approved quote is required before purchase.', 409, 'GATE_BLOCKED'); const { orderNumber } = z.object({ orderNumber: z.string().trim().min(3).max(100) }).parse(req.body); const po = await prisma.purchaseOrder.create({ data: { procurementRequestId: request.id, vendorId: quote.vendorId, orderNumber, subtotalCents: quote.amountCents, taxCents: quote.taxCents, approvedAmountCents: quote.totalCents, currencyCode: quote.currencyCode, costCode: request.costCode, authorizedBy: req.user!.id } }); await prisma.procurementRequest.update({ where: { id: request.id }, data: { status: 'ORDERED' } }); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'CREATE', entityType: 'PurchaseOrder', entityId: po.id, requestId: (req as any).requestId, after: po }); res.status(201).json(po); } catch (error) { next(error); }
});

router.post('/procurement/purchase-orders/:id/deliveries', async (req: AuthRequest, res, next) => {
  try { requireInternal(req.user); const po = await prisma.purchaseOrder.findUnique({ where: { id: req.params.id }, include: { request: true, deliveries: true } }); if (!po) throw new AppError('Purchase order not found.', 404, 'NOT_FOUND'); await assertProjectAccess(req.user, po.request.projectId); const data = z.object({ expectedAt: z.coerce.date().nullable().optional(), receivedAt: z.coerce.date().nullable().optional(), quantityReceived: z.number().positive(), condition: z.enum(['GOOD', 'DAMAGED', 'INCOMPLETE', 'REJECTED']) }).parse(req.body); const delivered = po.deliveries.filter((item) => item.inspectionStatus !== 'FAILED').reduce((sum, item) => sum + item.quantityReceived, 0) + data.quantityReceived; if (delivered > po.request.quantity * 1.05) throw new AppError('Delivered quantity exceeds the authorized quantity.', 409, 'CONFLICT'); const delivery = await prisma.delivery.create({ data: { ...data, purchaseOrderId: po.id } }); const status = delivered >= po.request.quantity ? 'DELIVERED' : 'PARTIALLY_DELIVERED'; await prisma.$transaction([prisma.purchaseOrder.update({ where: { id: po.id }, data: { status } }), prisma.procurementRequest.update({ where: { id: po.request.id }, data: { status } })]); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'RECEIVE', entityType: 'Delivery', entityId: delivery.id, requestId: (req as any).requestId, after: delivery }); res.status(201).json(delivery); } catch (error) { next(error); }
});

router.post('/procurement/deliveries/:id/inspect', approvalLimiter, async (req: AuthRequest, res, next) => {
  try { requireInternal(req.user); const before = await prisma.delivery.findUnique({ where: { id: req.params.id }, include: { purchaseOrder: { include: { request: true } } } }); if (!before) throw new AppError('Delivery not found.', 404, 'NOT_FOUND'); await assertProjectAccess(req.user, before.purchaseOrder.request.projectId); const data = z.object({ passed: z.boolean(), notes: z.string().trim().max(5000).optional() }).parse(req.body); if (!data.passed && !data.notes) throw new AppError('Inspection notes are required for a failed delivery.', 400, 'VALIDATION_ERROR'); const delivery = await prisma.delivery.update({ where: { id: before.id }, data: { inspectionStatus: data.passed ? 'PASSED' : 'FAILED', inspectionNotes: data.notes || null, inspectedBy: req.user!.id, inspectedAt: new Date() } }); if (!data.passed) { await prisma.procurementRequest.update({ where: { id: before.purchaseOrder.request.id }, data: { status: before.condition === 'DAMAGED' ? 'BACKORDERED' : 'BLOCKED' } }); if (before.purchaseOrder.request.ownerId && !(await prisma.notification.findFirst({ where: { userId: before.purchaseOrder.request.ownerId, type: 'DELIVERY_EXCEPTION', itemId: delivery.id } }))) await prisma.notification.create({ data: { userId: before.purchaseOrder.request.ownerId, type: 'DELIVERY_EXCEPTION', message: `Delivery inspection failed: ${before.purchaseOrder.request.description}`, itemId: delivery.id } }); } await writeAuditEvent(prisma, { userId: req.user!.id, action: data.passed ? 'APPROVE' : 'REJECT', entityType: 'Delivery', entityId: delivery.id, requestId: (req as any).requestId, before, after: delivery }); res.json(delivery); } catch (error) { next(error); }
});

router.post('/procurement/requests/:id/backorder', async (req: AuthRequest, res, next) => { try { requireInternal(req.user); const request = await findRequest(req, req.params.id); const record = await prisma.procurementRequest.update({ where: { id: request.id }, data: { status: 'BACKORDERED' } }); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'BACKORDER', entityType: 'ProcurementRequest', entityId: record.id, requestId: (req as any).requestId, before: request, after: record }); res.json(record); } catch (error) { next(error); } });

router.post('/procurement/requests/:id/substitutions', async (req: AuthRequest, res, next) => {
  try { requireInternal(req.user); const request = await findRequest(req, req.params.id); const data = substitutionSchema.parse(req.body); if (data.clientAuthorizationRequired && !request.clientVisible) throw new AppError('Client-authorized substitutions require a client-visible procurement request.', 400, 'VALIDATION_ERROR'); const substitution = await prisma.substitution.create({ data: { ...data, procurementRequestId: request.id, originalSpecification: request.specification, requestedBy: req.user!.id } }); await prisma.procurementRequest.update({ where: { id: request.id }, data: { status: 'AUTHORIZATION_REQUIRED' } }); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'CREATE', entityType: 'Substitution', entityId: substitution.id, requestId: (req as any).requestId, after: substitution }); res.status(201).json(substitution); } catch (error) { next(error); }
});

router.post('/procurement/substitutions/:id/approve', approvalLimiter, async (req: AuthRequest, res, next) => {
  try { requireInternal(req.user); const before = await prisma.substitution.findUnique({ where: { id: req.params.id }, include: { request: true } }); if (!before) throw new AppError('Substitution not found.', 404, 'NOT_FOUND'); await assertProjectAccess(req.user, before.request.projectId); if (!(await canAuthorize(req, before.request.projectId))) throw new AppError('Procurement authorization is required.', 403, 'FORBIDDEN'); const status = before.clientAuthorizationRequired ? 'WAITING_CLIENT' : 'APPROVED'; const substitution = await prisma.substitution.update({ where: { id: before.id }, data: { status, approvedBy: req.user!.id, approvedAt: new Date() } }); if (status === 'WAITING_CLIENT') { const project = await prisma.poolProject.findUniqueOrThrow({ where: { id: before.request.projectId } }); const users = await prisma.user.findMany({ where: { clientId: project.clientId, role: 'CLIENT', active: true }, select: { id: true } }); for (const user of users) await prisma.notification.create({ data: { userId: user.id, type: 'SUBSTITUTION_AUTHORIZATION', message: `Authorization requested for substitution: ${before.request.description}`, itemId: substitution.id, clientId: project.clientId } }); } await writeAuditEvent(prisma, { userId: req.user!.id, action: 'APPROVE', entityType: 'Substitution', entityId: substitution.id, requestId: (req as any).requestId, before, after: substitution }); res.json(substitution); } catch (error) { next(error); }
});

router.post('/procurement/substitutions/:id/client-authorize', approvalLimiter, async (req: AuthRequest, res, next) => {
  try { const before = await prisma.substitution.findUnique({ where: { id: req.params.id }, include: { request: true } }); if (!before) throw new AppError('Substitution not found.', 404, 'NOT_FOUND'); await assertProjectAccess(req.user, before.request.projectId); if (req.user?.role !== 'CLIENT' || !before.request.clientVisible || before.status !== 'WAITING_CLIENT') throw new AppError('This substitution is not available for client authorization.', 403, 'FORBIDDEN'); const substitution = await prisma.substitution.update({ where: { id: before.id }, data: { status: 'APPROVED', clientAuthorizedBy: req.user.id, clientAuthorizedAt: new Date() } }); await writeAuditEvent(prisma, { userId: req.user.id, action: 'AUTHORIZE', entityType: 'Substitution', entityId: substitution.id, requestId: (req as any).requestId, before, after: substitution }); res.json(substitution); } catch (error) { next(error); }
});

router.post('/procurement/requests/:id/invoice-match', async (req: AuthRequest, res, next) => {
  try { requireInternal(req.user); const request = await findRequest(req, req.params.id); if (!request.purchaseOrder) throw new AppError('Purchase order is required for invoice matching.', 409, 'GATE_BLOCKED'); const data = z.object({ invoiceReference: z.string().trim().min(2).max(100), deliveredAmountCents: money, invoicedAmountCents: money }).parse(req.body); const deliveredQuantity = request.purchaseOrder.deliveries.filter((item) => item.inspectionStatus === 'PASSED').reduce((sum, item) => sum + item.quantityReceived, 0); const varianceAmountCents = data.invoicedAmountCents - request.purchaseOrder.approvedAmountCents; const matched = deliveredQuantity >= request.quantity && Math.abs(varianceAmountCents) <= 1 && Math.abs(data.deliveredAmountCents - request.purchaseOrder.approvedAmountCents) <= 1; const match = await prisma.invoiceMatch.create({ data: { ...data, purchaseOrderId: request.purchaseOrder.id, orderedAmountCents: request.purchaseOrder.approvedAmountCents, varianceAmountCents, orderedQuantity: request.quantity, deliveredQuantity, currencyCode: request.purchaseOrder.currencyCode, status: matched ? 'MATCHED' : 'VARIANCE' } }); await prisma.procurementRequest.update({ where: { id: request.id }, data: { status: matched ? 'MATCHED' : 'INVOICED' } }); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'VERIFY', entityType: 'InvoiceMatch', entityId: match.id, requestId: (req as any).requestId, after: match }); res.status(201).json(match); } catch (error) { next(error); }
});

router.post('/procurement/requests/:id/close', async (req: AuthRequest, res, next) => { try { requireInternal(req.user); const request = await findRequest(req, req.params.id); const blockers = (await procurementBlockers(request.projectId)).filter((item) => item.type !== 'REQUEST_STATUS' && (item.id === request.id || request.substitutions.some((sub) => sub.id === item.id))); if (blockers.length) throw new AppError('Procurement request cannot close until verification is complete.', 409, 'GATE_BLOCKED', { blockers }); const record = await prisma.procurementRequest.update({ where: { id: request.id }, data: { status: 'CLOSED', closedAt: new Date() } }); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'CLOSE', entityType: 'ProcurementRequest', entityId: record.id, requestId: (req as any).requestId, before: request, after: record }); res.json(record); } catch (error) { next(error); } });

router.post('/projects/:projectId/procurement/gate/approve', approvalLimiter, async (req: AuthRequest, res, next) => {
  try { requireInternal(req.user); const project = await assertProjectAccess(req.user, req.params.projectId); if (!(await canAuthorize(req, project.id))) throw new AppError('Procurement gate authorization is required.', 403, 'FORBIDDEN'); if (project.currentLifecycleStage !== 'PROCUREMENT') throw new AppError('Project is not in Procurement.', 409, 'INVALID_TRANSITION'); const blockers = await procurementBlockers(project.id); const gate = await ensureProcurementGate(project.id); if (blockers.length) { await prisma.projectGate.update({ where: { id: gate.id }, data: { status: 'BLOCKED', blockerCount: blockers.length, requiredItems: JSON.stringify(blockers) } }); throw new AppError('Procurement handoff is blocked by unresolved conditions.', 409, 'GATE_BLOCKED', { blockers }); } const now = new Date(); const updatedGate = await prisma.$transaction(async (tx) => { const updated = await tx.projectGate.update({ where: { id: gate.id }, data: { status: 'APPROVED', blockerCount: 0, requiredItems: '[]', approvedBy: req.user!.id, approvedAt: now } }); await tx.approval.create({ data: { projectId: project.id, gateId: gate.id, approvalType: 'PROCUREMENT_HANDOFF', approverId: req.user!.id, result: 'APPROVED' } }); await tx.lifecycleStage.update({ where: { projectId_stage: { projectId: project.id, stage: 'PROCUREMENT' } }, data: { status: 'APPROVED', completedAt: now } }); await synchronizeLegacyPhases(tx, project.id, 'PROCUREMENT', req.user!.id, now); await tx.poolProject.update({ where: { id: project.id }, data: { status: 'FIELD_EXECUTION', currentLifecycleStage: null, workflowVersion: { increment: 1 } } }); await tx.client.update({ where: { id: project.clientId }, data: { status: 'ACTIVE' } }); return updated; }); await writeAuditEvent(prisma, { userId: req.user!.id, action: 'ADVANCE', entityType: 'ProjectGate', entityId: updatedGate.id, requestId: (req as any).requestId, after: { status: 'FIELD_EXECUTION' } }); res.json(updatedGate); } catch (error) { next(error); }
});

export default router;
