import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AlertCircle, ArrowLeft, CheckCircle2, Clock3, FileText, Plus, ShieldAlert } from 'lucide-react';
import { authApi, complianceApi, documentApi, getApiErrorMessage, toIsoDateTime, workflowApi } from '../api';
import { ComplianceRequirement, ComplianceWorkspace as Workspace, Document, GateBlocker, User } from '../types';
import { useAuth } from '../context/AuthContext';

const categories = ['HOA', 'MUNICIPAL', 'PERMIT', 'ENGINEERING', 'ARCHITECTURAL', 'DRAINAGE', 'GRADING', 'UTILITIES', 'ACCESS', 'CONSTRUCTABILITY'];
const activeStatuses = ['NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'PENDING_EXTERNAL', 'BLOCKED', 'REJECTED'];
const statusTone: Record<string, string> = {
  APPROVED: 'bg-green-100 text-green-800', REJECTED: 'bg-red-100 text-red-800', BLOCKED: 'bg-red-100 text-red-800',
  PENDING_EXTERNAL: 'bg-amber-100 text-amber-900', SUBMITTED: 'bg-blue-100 text-blue-800', IN_PROGRESS: 'bg-blue-50 text-blue-800',
  NOT_APPLICABLE: 'bg-gray-100 text-gray-600', NOT_STARTED: 'bg-gray-100 text-gray-700',
};

export default function ComplianceWorkspace() {
  const { projectId } = useParams<{ projectId: string }>();
  const { user } = useAuth();
  const internal = user?.role === 'ADMIN';
  const [data, setData] = useState<Workspace | null>(null);
  const [users, setUsers] = useState<User[]>([]);
  const [documents, setDocuments] = useState<Document[]>([]);
  const [blockers, setBlockers] = useState<GateBlocker[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [filter, setFilter] = useState('ALL');
  const [form, setForm] = useState({ category: 'HOA', description: '', jurisdiction: '', externalAgency: '', ownerId: '', reviewerId: '', dueAt: '', evidenceRequired: false, clientVisible: false, required: true });

  const load = async () => {
    if (!projectId) return;
    try {
      setLoading(true); setError('');
      const workspace = await complianceApi.getWorkspace(projectId);
      setData(workspace.data);
      if (internal) {
        const [userResult, documentResult, centerResult] = await Promise.all([
          authApi.getUsers(), documentApi.getAll(workspace.data.project.clientId), workflowApi.getCommandCenter(projectId),
        ]);
        setUsers((userResult.data.data || userResult.data).filter((item: User) => item.active && item.role === 'ADMIN'));
        setDocuments(documentResult.data.data || documentResult.data);
        setBlockers(centerResult.data.blockers || []);
      }
    } catch (err) { setError(getApiErrorMessage(err, 'The Compliance workspace could not be loaded.')); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, [projectId]);

  const mutate = async (operation: () => Promise<unknown>) => {
    try { setSaving(true); setError(''); await operation(); await load(); }
    catch (err) { setError(getApiErrorMessage(err, 'The Compliance change could not be saved.')); }
    finally { setSaving(false); }
  };
  const create = (event: FormEvent) => {
    event.preventDefault();
    mutate(async () => {
      await complianceApi.createRequirement(projectId!, { ...form, ownerId: form.ownerId || null, reviewerId: form.reviewerId || null, dueAt: toIsoDateTime(form.dueAt), jurisdiction: form.jurisdiction || null, externalAgency: form.externalAgency || null });
      setShowForm(false); setForm({ category: 'HOA', description: '', jurisdiction: '', externalAgency: '', ownerId: '', reviewerId: '', dueAt: '', evidenceRequired: false, clientVisible: false, required: true });
    });
  };
  const visible = useMemo(() => data?.requirements.filter((item) => filter === 'ALL' || item.category === filter || item.status === filter) || [], [data, filter]);
  const overdue = data?.requirements.filter((item) => item.required && item.dueAt && new Date(item.dueAt) < new Date() && !['APPROVED', 'NOT_APPLICABLE'].includes(item.status)).length || 0;
  const approved = data?.requirements.filter((item) => item.status === 'APPROVED').length || 0;

  if (loading) return <div className="flex min-h-64 items-center justify-center"><div className="h-9 w-9 animate-spin rounded-full border-4 border-emerald-200 border-t-emerald-600" /></div>;
  if (!data) return <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-red-800">{error || 'Compliance workspace unavailable.'}</div>;
  return <div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><Link to={internal ? `/projects/${projectId}` : '/my-project'} className="text-sm text-blue-700"><ArrowLeft className="mr-1 inline h-4 w-4" />Back</Link><h1 className="mt-2 text-2xl font-bold text-gray-950">{data.client.name} · Compliance register</h1><p className="mt-1 text-sm text-gray-600">Permits, HOA, engineering, site constraints, evidence, external responses, exceptions, and approval readiness.</p></div>{internal && <button onClick={() => setShowForm(!showForm)} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-medium text-white"><Plus className="mr-1 inline h-4 w-4" />New requirement</button>}</header>
    {error && <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertCircle className="mr-2 inline h-4 w-4" />{error}</div>}
    <section className="grid gap-4 md:grid-cols-4"><Metric label="Requirements" value={data.requirements.length} tone="slate" /><Metric label="Approved" value={approved} tone="green" /><Metric label="Awaiting action" value={data.requirements.filter((item)=>activeStatuses.includes(item.status)).length} tone="amber" /><Metric label="Overdue" value={overdue} tone={overdue ? 'red' : 'green'} /></section>
    {internal && <section className={`rounded-xl border p-5 ${blockers.length ? 'border-red-200 bg-red-50' : 'border-green-200 bg-green-50'}`}><div className="flex items-start gap-3">{blockers.length ? <ShieldAlert className="mt-0.5 h-5 w-5 text-red-700" /> : <CheckCircle2 className="mt-0.5 h-5 w-5 text-green-700" />}<div><h2 className="font-semibold">Compliance → Pre-Construction gate</h2><p className="mt-1 text-sm">{blockers.length ? `${blockers.length} blocker${blockers.length === 1 ? '' : 's'} must be resolved or covered by an approved exception.` : 'All current Compliance gate rules are satisfied.'}</p>{blockers.length > 0 && <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{blockers.map((item)=><li key={`${item.type}-${item.id}`}>{item.title}</li>)}</ul>}</div></div></section>}
    {showForm && <form onSubmit={create} className="grid gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-5 md:grid-cols-3"><h2 className="md:col-span-3 font-semibold">Add compliance requirement</h2><Select label="Category" value={form.category} set={(value)=>setForm({...form,category:value})} options={categories} /><Field label="Description" value={form.description} set={(value)=>setForm({...form,description:value})} required /><Field label="Jurisdiction" value={form.jurisdiction} set={(value)=>setForm({...form,jurisdiction:value})} /><Field label="External agency" value={form.externalAgency} set={(value)=>setForm({...form,externalAgency:value})} /><Select label="Owner" value={form.ownerId} set={(value)=>setForm({...form,ownerId:value})} options={users.map((item)=>item.id)} labels={Object.fromEntries(users.map((item)=>[item.id,item.name]))} empty="Unassigned" /><Select label="Reviewer" value={form.reviewerId} set={(value)=>setForm({...form,reviewerId:value})} options={users.map((item)=>item.id)} labels={Object.fromEntries(users.map((item)=>[item.id,item.name]))} empty="Unassigned" /><Field label="Due date" type="datetime-local" value={form.dueAt} set={(value)=>setForm({...form,dueAt:value})} /><div className="flex flex-wrap items-center gap-4 md:col-span-2"><Check label="Required" checked={form.required} set={(value)=>setForm({...form,required:value})} /><Check label="Evidence required" checked={form.evidenceRequired} set={(value)=>setForm({...form,evidenceRequired:value})} /><Check label="Client visible" checked={form.clientVisible} set={(value)=>setForm({...form,clientVisible:value})} /></div><button disabled={saving} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm text-white disabled:opacity-50">Create requirement</button></form>}
    <section className="rounded-xl border border-gray-200 bg-white p-4"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium text-gray-700">Filter:</span><button onClick={()=>setFilter('ALL')} className={pill(filter==='ALL')}>All</button>{categories.map((item)=><button key={item} onClick={()=>setFilter(item)} className={pill(filter===item)}>{pretty(item)}</button>)}<button onClick={()=>setFilter('REJECTED')} className={pill(filter==='REJECTED')}>Needs correction</button></div></section>
    <section className="space-y-4">{visible.length ? visible.map((item)=><RequirementCard key={item.id} item={item} internal={internal} admin={user?.role==='ADMIN'} users={users} documents={documents} saving={saving} mutate={mutate} />) : <div className="rounded-xl border border-dashed border-gray-300 bg-white p-10 text-center text-sm text-gray-500">No compliance requirements match this view.</div>}</section>
  </div>;
}

function RequirementCard({ item, internal, admin, users, documents, saving, mutate }: { item: ComplianceRequirement; internal: boolean; admin: boolean; users: User[]; documents: Document[]; saving: boolean; mutate: (operation:()=>Promise<unknown>)=>void }) {
  const [details, setDetails] = useState({ status: item.status, ownerId: item.ownerId || '', reviewerId: item.reviewerId || '', dueAt: item.dueAt ? item.dueAt.slice(0,16) : '', externalResponseAt: item.externalResponseAt ? item.externalResponseAt.slice(0,16) : '', clientVisible: item.clientVisible });
  const [evidence, setEvidence] = useState({ documentId: '', purpose: '' });
  const [showEvidence, setShowEvidence] = useState(false);
  const [showException, setShowException] = useState(false);
  const [exception, setException] = useState({ reason: '', risk: '', mitigation: '', ownerId: '', dueAt: '' });
  const overdue = item.required && item.dueAt && new Date(item.dueAt) < new Date() && !['APPROVED','NOT_APPLICABLE'].includes(item.status);
  const save = () => mutate(() => complianceApi.updateRequirement(item.id, { ...details, ownerId: details.ownerId || null, reviewerId: details.reviewerId || null, dueAt: toIsoDateTime(details.dueAt), externalResponseAt: toIsoDateTime(details.externalResponseAt) }));
  const reject = () => { const reason = window.prompt('Correction required'); if (reason) mutate(()=>complianceApi.reviewRequirement(item.id,false,reason)); };
  return <article className={`rounded-xl border bg-white p-5 ${overdue ? 'border-red-300' : 'border-gray-200'}`}><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-800">{pretty(item.category)}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusTone[item.status] || statusTone.NOT_STARTED}`}>{pretty(item.status)}</span>{item.required && <span className="text-xs font-medium text-gray-500">Required</span>}{item.clientVisible && <span className="text-xs font-medium text-blue-700">Client visible</span>}{overdue && <span className="inline-flex items-center gap-1 text-xs font-semibold text-red-700"><Clock3 className="h-3.5 w-3.5" />Overdue</span>}</div><h2 className="mt-3 font-semibold text-gray-950">{item.description}</h2><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-xs text-gray-500"><span>Owner: {item.owner?.name || 'Unassigned'}</span><span>Reviewer: {item.reviewer?.name || 'Unassigned'}</span><span>Due: {item.dueAt ? new Date(item.dueAt).toLocaleString() : 'Not set'}</span>{item.externalAgency && <span>Agency: {item.externalAgency}</span>}{item.jurisdiction && <span>Jurisdiction: {item.jurisdiction}</span>}</div></div><div className="flex flex-wrap gap-2">{internal && ['NOT_STARTED','IN_PROGRESS','REJECTED','BLOCKED'].includes(item.status) && <button disabled={saving} onClick={()=>mutate(()=>complianceApi.submitRequirement(item.id))} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-medium text-white">{item.status==='REJECTED'?'Resubmit':'Submit'}</button>}{internal && ['SUBMITTED','PENDING_EXTERNAL'].includes(item.status) && <><button disabled={saving} onClick={()=>mutate(()=>complianceApi.reviewRequirement(item.id,true))} className="rounded-lg bg-green-600 px-3 py-2 text-xs font-medium text-white">Approve</button><button disabled={saving} onClick={reject} className="rounded-lg bg-red-100 px-3 py-2 text-xs font-medium text-red-800">Reject</button></>}</div></div>
    {item.rejectionReason && <div className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800"><strong>Correction required:</strong> {item.rejectionReason}</div>}
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="rounded-lg bg-gray-50 p-4"><h3 className="text-sm font-semibold"><FileText className="mr-1 inline h-4 w-4 text-blue-600" />Evidence {item.evidenceRequired && '(required)'}</h3><div className="mt-2 space-y-1">{item.evidenceLinks.length ? item.evidenceLinks.map((link)=><p key={link.id} className="text-xs text-gray-700">{link.document.originalName} · {link.purpose}</p>) : <p className="text-xs text-gray-500">No evidence linked.</p>}</div>{internal && <><button onClick={()=>setShowEvidence(!showEvidence)} className="mt-3 text-xs font-medium text-blue-700">{showEvidence?'Cancel':'Link evidence'}</button>{showEvidence && <div className="mt-2 grid gap-2"><select aria-label="Evidence document" value={evidence.documentId} onChange={(e)=>setEvidence({...evidence,documentId:e.target.value})} className="rounded border border-gray-300 px-2 py-1.5 text-sm"><option value="">Choose document</option>{documents.map((doc)=><option key={doc.id} value={doc.id}>{doc.originalName}</option>)}</select><input aria-label="Evidence purpose" value={evidence.purpose} onChange={(e)=>setEvidence({...evidence,purpose:e.target.value})} placeholder="Purpose" className="rounded border border-gray-300 px-2 py-1.5 text-sm" /><button disabled={!evidence.documentId||evidence.purpose.length<3} onClick={()=>mutate(()=>complianceApi.linkEvidence(item.id,evidence))} className="rounded bg-blue-600 px-3 py-2 text-xs text-white disabled:opacity-40">Attach</button></div>}</>}</section>
      <section className="rounded-lg bg-gray-50 p-4"><h3 className="text-sm font-semibold"><ShieldAlert className="mr-1 inline h-4 w-4 text-amber-700" />Exceptions</h3><div className="mt-2 space-y-2">{item.exceptions.length ? item.exceptions.map((entry)=><div key={entry.id} className="rounded border border-gray-200 bg-white p-2 text-xs"><div className="flex justify-between gap-2"><span>{entry.reason}</span><span className="font-semibold">{entry.status}</span></div><p className="mt-1 text-gray-500">Risk: {entry.risk} · Mitigation: {entry.mitigation}</p>{admin && entry.status==='PENDING' && <button onClick={()=>mutate(()=>complianceApi.approveException(entry.id))} className="mt-2 rounded bg-amber-700 px-2 py-1 text-white">Leadership approve</button>}</div>) : <p className="text-xs text-gray-500">No exceptions recorded.</p>}</div>{internal && <><button onClick={()=>setShowException(!showException)} className="mt-3 text-xs font-medium text-amber-800">{showException?'Cancel':'Request controlled exception'}</button>{showException && <div className="mt-2 grid gap-2"><input value={exception.reason} onChange={(e)=>setException({...exception,reason:e.target.value})} placeholder="Reason (10+ characters)" className="rounded border px-2 py-1.5 text-sm" /><input value={exception.risk} onChange={(e)=>setException({...exception,risk:e.target.value})} placeholder="Accepted risk" className="rounded border px-2 py-1.5 text-sm" /><input value={exception.mitigation} onChange={(e)=>setException({...exception,mitigation:e.target.value})} placeholder="Mitigation" className="rounded border px-2 py-1.5 text-sm" /><select value={exception.ownerId} onChange={(e)=>setException({...exception,ownerId:e.target.value})} className="rounded border px-2 py-1.5 text-sm"><option value="">Risk owner</option>{users.map((entry)=><option key={entry.id} value={entry.id}>{entry.name}</option>)}</select><input type="datetime-local" value={exception.dueAt} onChange={(e)=>setException({...exception,dueAt:e.target.value})} className="rounded border px-2 py-1.5 text-sm" /><button disabled={exception.reason.length<10||!exception.risk||!exception.mitigation||!exception.ownerId||!exception.dueAt} onClick={()=>mutate(()=>complianceApi.createException(item.id,exception))} className="rounded bg-amber-700 px-3 py-2 text-xs text-white disabled:opacity-40">Record exception</button></div>}</>}</section></div>
    {internal && <details className="mt-4"><summary className="cursor-pointer text-sm font-medium text-gray-700">Assignment, dates, visibility, and status</summary><div className="mt-3 grid gap-3 rounded-lg border border-gray-200 p-4 md:grid-cols-3"><Select label="Status" value={details.status} set={(value)=>setDetails({...details,status:value})} options={['NOT_STARTED','IN_PROGRESS','PENDING_EXTERNAL','BLOCKED','NOT_APPLICABLE']} /><Select label="Owner" value={details.ownerId} set={(value)=>setDetails({...details,ownerId:value})} options={users.map((entry)=>entry.id)} labels={Object.fromEntries(users.map((entry)=>[entry.id,entry.name]))} empty="Unassigned" /><Select label="Reviewer" value={details.reviewerId} set={(value)=>setDetails({...details,reviewerId:value})} options={users.map((entry)=>entry.id)} labels={Object.fromEntries(users.map((entry)=>[entry.id,entry.name]))} empty="Unassigned" /><Field label="Due date" type="datetime-local" value={details.dueAt} set={(value)=>setDetails({...details,dueAt:value})} /><Field label="External response" type="datetime-local" value={details.externalResponseAt} set={(value)=>setDetails({...details,externalResponseAt:value})} /><div className="flex items-end justify-between gap-3"><Check label="Client visible" checked={details.clientVisible} set={(value)=>setDetails({...details,clientVisible:value})} /><button disabled={saving} onClick={save} className="rounded bg-gray-900 px-3 py-2 text-xs text-white">Save details</button></div></div></details>}
  </article>;
}

function Metric({label,value,tone}:{label:string;value:number;tone:'slate'|'green'|'amber'|'red'}) { const colors={slate:'border-gray-200 bg-white text-gray-900',green:'border-green-200 bg-green-50 text-green-900',amber:'border-amber-200 bg-amber-50 text-amber-900',red:'border-red-200 bg-red-50 text-red-900'}; return <div className={`rounded-xl border p-4 ${colors[tone]}`}><p className="text-sm font-medium">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div>; }
function Field({label,value,set,type='text',required}:{label:string;value:string;set:(value:string)=>void;type?:string;required?:boolean}) { return <label className="text-sm font-medium">{label}<input required={required} type={type} value={value} onChange={(e)=>set(e.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2" /></label>; }
function Select({label,value,set,options,labels={},empty}:{label:string;value:string;set:(value:string)=>void;options:string[];labels?:Record<string,string>;empty?:string}) { return <label className="text-sm font-medium">{label}<select value={value} onChange={(e)=>set(e.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2">{empty && <option value="">{empty}</option>}{options.map((option)=><option key={option} value={option}>{labels[option]||pretty(option)}</option>)}</select></label>; }
function Check({label,checked,set}:{label:string;checked:boolean;set:(value:boolean)=>void}) { return <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={checked} onChange={(e)=>set(e.target.checked)} />{label}</label>; }
function pretty(value:string) { return value.replace(/_/g,' ').replace(/\b\w/g,(letter)=>letter.toUpperCase()); }
function pill(selected:boolean) { return `rounded-full px-3 py-1.5 text-xs font-medium ${selected?'bg-gray-900 text-white':'bg-gray-100 text-gray-700 hover:bg-gray-200'}`; }
