import { FormEvent, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AlertCircle, ArrowLeft, CheckCircle2, FileText, GitCompare, HelpCircle, Plus } from 'lucide-react';
import { designApi, documentApi, getApiErrorMessage, workflowApi } from '../api';
import { DesignVersion, DesignWorkspace as Workspace, Document, ScopeVersion } from '../types';
import { useAuth } from '../context/AuthContext';

export default function DesignWorkspace() {
  const { projectId } = useParams<{projectId:string}>();
  const { user } = useAuth();
  const internal = user?.role === 'ADMIN';
  const [data, setData] = useState<Workspace | null>(null);
  const [documents, setDocuments] = useState<Document[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [showDesign, setShowDesign] = useState(false);
  const [showScope, setShowScope] = useState(false);
  const [question, setQuestion] = useState('');
  const [designForm, setDesignForm] = useState({ summary: '', requirements: '', siteInformation: '', changeSummary: '', costImpact: '', scheduleImpact: '', materialChange: false });
  const [scopeForm, setScopeForm] = useState({ inclusions: '', exclusions: '', allowances: '', estimateAmount: '', changeSummary: '', scheduleImpact: '', materialChange: false });
  const [evidenceForm, setEvidenceForm] = useState({ documentId: '', target: '', purpose: '' });

  const load = async () => {
    if (!projectId) return;
    try {
      setLoading(true); setError('');
      const workspace = await designApi.getWorkspace(projectId);
      setData(workspace.data);
      if (internal) setDocuments((await documentApi.getAll(workspace.data.project.clientId)).data.data);
    } catch (err) { setError(getApiErrorMessage(err, 'The Design workspace could not be loaded.')); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, [projectId]);

  const mutate = async (operation: () => Promise<unknown>) => {
    try { setSaving(true); setError(''); await operation(); await load(); }
    catch (err) { setError(getApiErrorMessage(err, 'The requested Design change could not be saved.')); }
    finally { setSaving(false); }
  };

  const createDesign = (event: FormEvent) => { event.preventDefault(); mutate(async () => { await designApi.createDesignVersion(projectId!, { ...designForm, costImpact: designForm.costImpact || null }); setShowDesign(false); }); };
  const createScope = (event: FormEvent) => { event.preventDefault(); mutate(async () => { await designApi.createScopeVersion(projectId!, { ...scopeForm, estimateAmount: scopeForm.estimateAmount || null }); setShowScope(false); }); };
  const reject = (kind: 'design'|'scope', id: string) => { const comment = window.prompt('What must change before approval?'); if (!comment) return; mutate(() => kind === 'design' ? designApi.rejectDesign(id, comment) : designApi.rejectScope(id, comment)); };

  if (loading) return <div className="flex min-h-64 items-center justify-center"><div className="h-9 w-9 animate-spin rounded-full border-4 border-blue-200 border-t-blue-600" /></div>;
  if (!data) return <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-red-800">{error || 'Design workspace unavailable.'}</div>;
  const pendingDesign = data.designVersions.filter((item) => item.status === 'IN_REVIEW');
  const pendingScope = data.scopeVersions.filter((item) => item.status === 'IN_REVIEW');

  return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><Link to={internal ? `/projects/${projectId}` : '/my-project'} className="text-sm text-blue-700"><ArrowLeft className="mr-1 inline h-4 w-4" />Back</Link><h1 className="mt-2 text-2xl font-bold text-gray-950">{data.client.name} · Design and scope</h1><p className="mt-1 text-sm text-gray-600">Requirements, design direction, scope authorization, impacts, evidence, and open questions.</p></div>{internal && <div className="flex gap-2"><button onClick={() => setShowDesign(!showDesign)} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white"><Plus className="mr-1 inline h-4 w-4" />Design version</button><button onClick={() => setShowScope(!showScope)} className="rounded-lg bg-gray-900 px-4 py-2 text-sm font-medium text-white"><Plus className="mr-1 inline h-4 w-4" />Scope version</button></div>}</header>
    {error && <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertCircle className="mr-2 inline h-4 w-4" />{error}</div>}
    <section className="grid gap-4 md:grid-cols-3"><Summary label="Project objectives" value={data.inquiry?.objectives} /><Summary label="Preliminary scope" value={data.inquiry?.preliminaryScope} /><Summary label="Site" value={data.properties[0] ? `${data.properties[0].address}, ${data.properties[0].city || ''} ${data.properties[0].state || ''}` : null} /></section>
    {internal && data.inquiry?.discovery && <details className="rounded-xl border border-blue-200 bg-white" open><summary className="cursor-pointer px-5 py-4 font-semibold text-blue-950">Reception discovery brief</summary><div className="grid gap-4 border-t border-blue-100 p-5 md:grid-cols-2 xl:grid-cols-3"><Summary label="Project type" value={data.inquiry.discovery.projectType}/><Summary label="Primary use" value={data.inquiry.discovery.primaryUse}/><Summary label="Decision makers" value={data.inquiry.discovery.decisionMakers}/><Summary label="Property access" value={data.inquiry.discovery.propertyAccess}/><Summary label="Site conditions" value={data.inquiry.discovery.siteConditions}/><Summary label="Utilities and constraints" value={data.inquiry.discovery.utilities}/><Summary label="Survey status" value={data.inquiry.discovery.surveyStatus}/><Summary label="Must-have features" value={data.inquiry.discovery.mustHaveFeatures}/><Summary label="Style preferences" value={data.inquiry.discovery.stylePreferences}/><Summary label="Outdoor scope" value={data.inquiry.discovery.deckingOutdoorScope}/><Summary label="Working investment" value={data.inquiry.discovery.budgetRange}/><Summary label="Target completion" value={data.inquiry.discovery.targetCompletion}/><Summary label="Priority tradeoffs" value={data.inquiry.discovery.priorityTradeoffs}/><Summary label="Known concerns" value={data.inquiry.discovery.knownConcerns}/><Summary label="Representative notes" value={data.inquiry.discovery.representativeNotes}/></div></details>}
    {showDesign && <form onSubmit={createDesign} className="grid gap-3 rounded-xl border border-blue-200 bg-blue-50 p-5 md:grid-cols-2"><h2 className="md:col-span-2 font-semibold">New design revision</h2><Area label="Design summary" value={designForm.summary} set={(value)=>setDesignForm({...designForm,summary:value})} required /><Area label="Requirements" value={designForm.requirements} set={(value)=>setDesignForm({...designForm,requirements:value})} /><Area label="Site information" value={designForm.siteInformation} set={(value)=>setDesignForm({...designForm,siteInformation:value})} /><Area label="Change summary" value={designForm.changeSummary} set={(value)=>setDesignForm({...designForm,changeSummary:value})} /><Field label="Cost impact" type="number" value={designForm.costImpact} set={(value)=>setDesignForm({...designForm,costImpact:value})} /><Field label="Schedule impact" value={designForm.scheduleImpact} set={(value)=>setDesignForm({...designForm,scheduleImpact:value})} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={designForm.materialChange} onChange={(e)=>setDesignForm({...designForm,materialChange:e.target.checked})} />Material change that invalidates prior approval</label><button disabled={saving} className="rounded-lg bg-blue-600 px-4 py-2 text-sm text-white disabled:opacity-50">Create draft</button></form>}
    {showScope && <form onSubmit={createScope} className="grid gap-3 rounded-xl border border-gray-300 bg-gray-50 p-5 md:grid-cols-2"><h2 className="md:col-span-2 font-semibold">New scope revision</h2><Area label="Inclusions" value={scopeForm.inclusions} set={(value)=>setScopeForm({...scopeForm,inclusions:value})} required /><Area label="Exclusions" value={scopeForm.exclusions} set={(value)=>setScopeForm({...scopeForm,exclusions:value})} /><Area label="Allowances" value={scopeForm.allowances} set={(value)=>setScopeForm({...scopeForm,allowances:value})} /><Area label="Change summary" value={scopeForm.changeSummary} set={(value)=>setScopeForm({...scopeForm,changeSummary:value})} /><Field label="Estimate amount" type="number" value={scopeForm.estimateAmount} set={(value)=>setScopeForm({...scopeForm,estimateAmount:value})} /><Field label="Schedule impact" value={scopeForm.scheduleImpact} set={(value)=>setScopeForm({...scopeForm,scheduleImpact:value})} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={scopeForm.materialChange} onChange={(e)=>setScopeForm({...scopeForm,materialChange:e.target.checked})} />Material change that invalidates prior approval</label><button disabled={saving} className="rounded-lg bg-gray-900 px-4 py-2 text-sm text-white disabled:opacity-50">Create draft</button></form>}
    {(pendingDesign.length > 0 || pendingScope.length > 0) && <section className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-950">Approval required</h2><div className="mt-3 space-y-2">{pendingDesign.map((version)=><ApprovalRow key={version.id} label={`Design v${version.versionNumber}: ${version.summary}`} onApprove={()=>mutate(()=>designApi.approveDesign(version.id))} onReject={()=>reject('design',version.id)} />)}{pendingScope.map((version)=><ApprovalRow key={version.id} label={`Scope v${version.versionNumber}: ${version.inclusions}`} onApprove={()=>mutate(()=>designApi.approveScope(version.id))} onReject={()=>reject('scope',version.id)} />)}</div></section>}
    <div className="grid gap-6 xl:grid-cols-2"><VersionPanel title="Design revisions" versions={data.designVersions} type="design" internal={internal} saving={saving} onSubmit={(id)=>mutate(()=>designApi.submitDesign(id))} /><VersionPanel title="Scope revisions" versions={data.scopeVersions} type="scope" internal={internal} saving={saving} onSubmit={(id)=>mutate(()=>designApi.submitScope(id))} /></div>
    {internal && <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-semibold"><HelpCircle className="mr-2 inline h-5 w-5 text-amber-600" />Outstanding questions</h2><div className="mt-3 space-y-2">{data.outstandingQuestions.map((item)=><p key={item.id} className="rounded-lg bg-amber-50 p-3 text-sm">{item.title} · {item.status.replace(/_/g,' ')}</p>)}</div><div className="mt-3 flex gap-2"><input aria-label="Outstanding question" value={question} onChange={(e)=>setQuestion(e.target.value)} placeholder="Question or unresolved design choice" className="flex-1 rounded-lg border border-gray-300 px-3 py-2 text-sm" /><button onClick={()=>question && mutate(async()=>{await workflowApi.createWorkItem(projectId!,{stage:'DESIGN',type:'OUTSTANDING_QUESTION',title:question,clientVisible:true});setQuestion('');})} className="rounded-lg bg-amber-600 px-3 py-2 text-sm text-white">Add</button></div></section>
      <section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-semibold"><FileText className="mr-2 inline h-5 w-5 text-blue-600" />Relational evidence</h2><div className="mt-3 space-y-2">{data.evidence.map((link)=><p key={link.id} className="text-sm">{link.document.originalName} · {link.purpose}</p>)}</div><div className="mt-3 grid gap-2"><select aria-label="Evidence document" value={evidenceForm.documentId} onChange={(e)=>setEvidenceForm({...evidenceForm,documentId:e.target.value})} className="rounded-lg border border-gray-300 px-3 py-2 text-sm"><option value="">Choose document</option>{documents.map((document)=><option key={document.id} value={document.id}>{document.originalName}</option>)}</select><select aria-label="Evidence target" value={evidenceForm.target} onChange={(e)=>setEvidenceForm({...evidenceForm,target:e.target.value})} className="rounded-lg border border-gray-300 px-3 py-2 text-sm"><option value="">Choose version</option>{data.designVersions.map((version)=><option key={version.id} value={`design:${version.id}`}>Design v{version.versionNumber}</option>)}{data.scopeVersions.map((version)=><option key={version.id} value={`scope:${version.id}`}>Scope v{version.versionNumber}</option>)}</select><input aria-label="Evidence purpose" value={evidenceForm.purpose} onChange={(e)=>setEvidenceForm({...evidenceForm,purpose:e.target.value})} placeholder="Purpose" className="rounded-lg border border-gray-300 px-3 py-2 text-sm" /><button onClick={()=>mutate(()=>{const [type,id]=evidenceForm.target.split(':');return designApi.linkEvidence(projectId!,{documentId:evidenceForm.documentId,purpose:evidenceForm.purpose,[type==='design'?'designVersionId':'scopeVersionId']:id});})} disabled={!evidenceForm.documentId||!evidenceForm.target||!evidenceForm.purpose} className="rounded-lg bg-blue-600 px-3 py-2 text-sm text-white disabled:opacity-40">Link evidence</button></div></section></div>}
  </div>;
}

function VersionPanel({title,versions,type,internal,saving,onSubmit}:{title:string;versions:Array<DesignVersion|ScopeVersion>;type:'design'|'scope';internal:boolean;saving:boolean;onSubmit:(id:string)=>void}) { return <section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-semibold"><GitCompare className="mr-2 inline h-5 w-5 text-violet-600" />{title}</h2><div className="mt-4 space-y-3">{versions.length ? versions.map((version)=><article key={version.id} className="rounded-lg border border-gray-200 p-4"><div className="flex items-center justify-between gap-2"><p className="font-medium">Version {version.versionNumber}</p><span className={`rounded-full px-2 py-1 text-xs font-semibold ${version.status==='APPROVED'?'bg-green-100 text-green-800':version.status==='REJECTED'?'bg-red-100 text-red-800':'bg-gray-100 text-gray-700'}`}>{version.status}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-gray-700">{'summary' in version ? version.summary : version.inclusions}</p>{version.changeSummary && <p className="mt-2 text-xs text-gray-500">Change: {version.changeSummary}</p>}<div className="mt-2 flex flex-wrap gap-3 text-xs text-gray-500">{'costImpact' in version && version.costImpact && <span>Cost: {version.currency} {String(version.costImpact)}</span>}{'estimateAmount' in version && version.estimateAmount && <span>Estimate: {version.currency} {String(version.estimateAmount)}</span>}{version.scheduleImpact && <span>Schedule: {version.scheduleImpact}</span>}</div>{internal && version.status==='DRAFT' && <button disabled={saving} onClick={()=>onSubmit(version.id)} className="mt-3 rounded-lg bg-blue-600 px-3 py-2 text-xs font-medium text-white">Submit for approval</button>}</article>) : <p className="rounded-lg border border-dashed p-5 text-center text-sm text-gray-500">No {type} versions yet.</p>}</div></section>; }
function ApprovalRow({label,onApprove,onReject}:{label:string;onApprove:()=>void;onReject:()=>void}) { return <div className="flex flex-col justify-between gap-3 rounded-lg bg-white p-3 sm:flex-row sm:items-center"><p className="text-sm text-gray-900">{label}</p><div className="flex gap-2"><button onClick={onApprove} className="rounded-lg bg-green-600 px-3 py-2 text-xs font-medium text-white"><CheckCircle2 className="mr-1 inline h-4 w-4" />Approve</button><button onClick={onReject} className="rounded-lg bg-red-100 px-3 py-2 text-xs font-medium text-red-800">Request changes</button></div></div>; }
function Summary({label,value}:{label:string;value?:string|null}) { return <div className="rounded-xl border border-gray-200 bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-gray-500">{label}</p><p className="mt-2 text-sm text-gray-900">{value||'Not captured'}</p></div>; }
function Field({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}) { return <label className="text-sm font-medium">{label}<input type={type} value={value} onChange={(e)=>set(e.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2" /></label>; }
function Area({label,value,set,required}:{label:string;value:string;set:(v:string)=>void;required?:boolean}) { return <label className="text-sm font-medium">{label}<textarea required={required} rows={4} value={value} onChange={(e)=>set(e.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2" /></label>; }
