import { useEffect, useState } from 'react';
import { AlertCircle, Bot, CheckCircle2, RefreshCw, ShieldCheck, Truck } from 'lucide-react';
import { authApi, automationApi, getApiErrorMessage, managementApi } from '../api';
import { AutomationSuggestion, ManagementDashboard as DashboardData, NotificationDelivery, NotificationTrigger, User } from '../types';
import { useAuth } from '../context/AuthContext';

const pretty=(value:string)=>value.replace(/_/g,' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());
const tone=(value:string)=>value==='SENT'||value==='ACCEPTED'||value==='COMPLETED'?'bg-green-100 text-green-800':value==='FAILED'||value==='REJECTED'||value==='COMPLETED_WITH_ERRORS'?'bg-red-100 text-red-800':'bg-amber-100 text-amber-900';

export default function ManagementDashboard(){
  const{user:currentUser}=useAuth();
  const[data,setData]=useState<DashboardData|null>(null); const[suggestions,setSuggestions]=useState<AutomationSuggestion[]>([]);
  const[deliveries,setDeliveries]=useState<NotificationDelivery[]>([]); const[matrix,setMatrix]=useState<NotificationTrigger[]>([]);
  const[loading,setLoading]=useState(true); const[working,setWorking]=useState(''); const[error,setError]=useState(''); const[notice,setNotice]=useState('');
  const load=async()=>{try{setLoading(true);setError('');const[d,s,n,m]=await Promise.all([managementApi.getDashboard(),automationApi.getSuggestions(),automationApi.getDeliveries(),automationApi.getNotificationMatrix()]);setData(d.data);setSuggestions(s.data.data);setDeliveries(n.data.data);setMatrix(m.data.data);}catch(err){setError(getApiErrorMessage(err,'Management reporting could not be loaded.'));}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const act=async(key:string,op:()=>Promise<unknown>,message:string)=>{try{setWorking(key);setError('');setNotice('');await op();setNotice(message);await load();}catch(err){setError(getApiErrorMessage(err,'The management action could not be completed.'));}finally{setWorking('');}};
  if(loading&&!data)return <div className="py-16 text-center text-gray-500">Loading management controls…</div>; if(!data)return <div role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</div>;
  const pending=suggestions.filter((item)=>item.status==='PENDING_REVIEW'); const failures=deliveries.filter((item)=>item.status==='FAILED');
  return <div className="space-y-7">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wide text-blue-700">Operations control room</p><h1 className="mt-1 text-3xl font-bold text-gray-900">Management & automation</h1><p className="mt-2 max-w-3xl text-sm text-gray-600">Live metrics are calculated from authoritative workflow records. Automation only creates notices and reviewable suggestions; it cannot approve decisions, clear gates, or change project state.</p></div><button disabled={!!working} onClick={()=>act('run',()=>automationApi.run(),'Safe automation scan completed. Review any resulting suggestions below.')} className="rounded-lg bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><RefreshCw className={`mr-2 inline h-4 w-4 ${working==='run'?'animate-spin':''}`}/>Run safe automation scan</button></header>
    {error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertCircle className="mr-2 inline h-4 w-4"/>{error}</div>}{notice&&<div role="status" className="rounded-lg border border-green-200 bg-green-50 p-4 text-sm text-green-800"><CheckCircle2 className="mr-2 inline h-4 w-4"/>{notice}</div>}
    <section aria-label="Management overview" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Active projects" value={data.overview.activeProjects}/><Metric label="Open work" value={data.overview.openWorkItems}/><Metric label="Pending decisions" value={data.overview.pendingDecisions}/><Metric label="Gate blockers" value={data.overview.gateBlockers} warn={data.overview.gateBlockers>0}/><Metric label="Automation failures" value={data.overview.automationFailures} warn={data.overview.automationFailures>0}/></section>
    <section className="grid gap-5 xl:grid-cols-2"><Panel title="Stage aging" icon={<RefreshCw className="h-5 w-5"/>}><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-gray-500"><tr><th className="p-2">Client</th><th className="p-2">Stage</th><th className="p-2">Age</th><th className="p-2">Status</th></tr></thead><tbody>{data.stageAging.map((row)=><tr key={row.projectId} className="border-t"><td className="p-2 font-medium">{row.client}</td><td className="p-2">{pretty(row.stage)}</td><td className="p-2">{row.ageDays==null?'—':`${row.ageDays}d`}</td><td className="p-2">{pretty(row.status)}</td></tr>)}</tbody></table>{!data.stageAging.length&&<Empty text="No workflow projects yet."/>}</div></Panel><Panel title="Blockers & exceptions" icon={<AlertCircle className="h-5 w-5"/>}><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(data.blockers).map(([key,value])=><SmallMetric key={key} label={pretty(key)} value={value}/>)}</div></Panel></section>
    <section className="grid gap-5 lg:grid-cols-3"><Panel title="Compliance" icon={<ShieldCheck className="h-5 w-5"/>}><MetricRows rows={[['Approved',`${data.compliance.approved}/${data.compliance.required} required`],['Overdue',data.compliance.overdue],['Evidence missing',data.compliance.evidenceMissing],...Object.entries(data.compliance.byStatus).map(([k,v])=>[pretty(k),v] as [string,string|number])]}/></Panel><Panel title="Construction readiness" icon={<CheckCircle2 className="h-5 w-5"/>}><MetricRows rows={[['Reviews',data.readiness.latestReviews],['Pass rate',`${data.readiness.passRate}%`],['Average score',`${data.readiness.averageScore}%`],['Open exceptions',data.readiness.openExceptions]]}/></Panel><Panel title="Procurement" icon={<Truck className="h-5 w-5"/>}><MetricRows rows={[['Open requests',`${data.procurement.openRequests}/${data.procurement.requests}`],['Purchase orders',data.procurement.ordered],['On-time delivery',`${data.procurement.onTimeDeliveryRate}%`],['Inspection exceptions',`${data.procurement.inspectionExceptionRate}%`],['Invoice variances',data.procurement.amountVariances],['Substitutions',data.procurement.substitutions]]}/></Panel></section>
    <section className="grid gap-5 xl:grid-cols-2"><Panel title="Client experience" icon={<CheckCircle2 className="h-5 w-5"/>}><MetricRows rows={[['Median inquiry acknowledgment',data.clientExperience.medianInquiryAcknowledgmentMinutes==null?'No data':`${data.clientExperience.medianInquiryAcknowledgmentMinutes} min`],['Open client actions',data.clientExperience.openClientActions],['Overdue client actions',data.clientExperience.overdueClientActions],['On-time action rate',`${data.clientExperience.onTimeActionRate}%`],['Pending client decisions',data.clientExperience.pendingClientDecisions],['Communications, 30 days',data.clientExperience.communicationsLast30Days],['Satisfaction','Not yet collected']]}/></Panel><Panel title="Automation health" icon={<Bot className="h-5 w-5"/>}><MetricRows rows={[['Runs',data.automation.runs],['Failed / partial',`${data.automation.failedRuns} / ${data.automation.partialRuns}`],['Open operational alerts',data.automation.openOperationalAlerts],['Pending review',data.automation.pendingSuggestions],['Accepted / rejected',`${data.automation.acceptedSuggestions} / ${data.automation.rejectedSuggestions}`],['Delivery failed / pending / sent',`${data.automation.failedDeliveries} / ${data.automation.pendingDeliveries} / ${data.automation.sentDeliveries}`]]}/></Panel></section>
    {currentUser?.role==='ADMIN'&&<AccountAdministration currentUserId={currentUser.id}/>}
    <Panel title={`Human review queue (${pending.length})`} icon={<Bot className="h-5 w-5"/>}><div className="mb-4 rounded-lg border border-violet-200 bg-violet-50 p-4 text-sm text-violet-900"><strong>Human control is mandatory.</strong> Suggested values are non-authoritative until an internal user explicitly accepts or rejects them. Accepting a suggestion does not change source records; “Accept & create task” creates a traceable internal follow-up.</div><div className="space-y-4">{pending.map((item)=><SuggestionCard key={item.id} item={item} working={working} act={act}/>) }{!pending.length&&<Empty text="No suggestions are awaiting review."/>}</div></Panel>
    <Panel title={`External delivery outbox (${failures.length} failed)`} icon={<Truck className="h-5 w-5"/>}><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-xs uppercase text-gray-500"><tr><th className="p-2">Notice</th><th className="p-2">Channel</th><th className="p-2">Destination</th><th className="p-2">Status</th><th className="p-2">Attempts</th><th className="p-2">Action</th></tr></thead><tbody>{deliveries.map((item)=><tr key={item.id} className="border-t"><td className="p-2"><span className="block font-medium">{pretty(item.notification.type)}</span>{item.lastError&&<span className="block max-w-md text-xs text-red-700">{item.lastError}</span>}</td><td className="p-2">{item.channel}</td><td className="p-2">{item.destination}</td><td className="p-2"><Badge value={item.status}/></td><td className="p-2">{item.attemptCount}</td><td className="p-2">{item.status==='FAILED'?<button disabled={!!working} onClick={()=>act(item.id,()=>automationApi.retryDelivery(item.id),'Delivery retry recorded.')} className="font-medium text-blue-700 disabled:opacity-40">Retry</button>:'—'}</td></tr>)}</tbody></table>{!deliveries.length&&<Empty text="No external deliveries have been queued."/>}</div></Panel>
    <Panel title="Notification trigger matrix" icon={<ShieldCheck className="h-5 w-5"/>}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="text-xs uppercase text-gray-500"><tr><th className="p-2">Trigger</th><th className="p-2">Notice type</th><th className="p-2">Recipients</th><th className="p-2">Delivery</th></tr></thead><tbody>{matrix.map((item)=><tr key={item.type} className="border-t"><td className="p-2 font-medium">{item.trigger}</td><td className="p-2">{pretty(item.type)}</td><td className="p-2">{item.recipients}</td><td className="p-2">{item.delivery.join(' + ')}</td></tr>)}</tbody></table></div></Panel>
    <p className="text-xs text-gray-500">Metrics generated {new Date(data.generatedAt).toLocaleString()}. Satisfaction remains explicitly unavailable until a validated survey source is configured.</p>
  </div>;
}

function AccountAdministration({currentUserId}:{currentUserId:string}){
  const[users,setUsers]=useState<User[]>([]);const[userId,setUserId]=useState('');const[password,setPassword]=useState('');
  const[message,setMessage]=useState('');const[error,setError]=useState('');const[saving,setSaving]=useState(false);
  const loadUsers=()=>authApi.getUsers().then((response)=>setUsers(response.data));
  useEffect(()=>{loadUsers().catch((err)=>setError(getApiErrorMessage(err,'User accounts could not be loaded.')));},[]);
  const resetPassword=async(event:React.FormEvent)=>{event.preventDefault();try{setSaving(true);setError('');setMessage('');const response=await authApi.resetUserPassword(userId,password);setMessage(response.data.message);setPassword('');}catch(err){setError(getApiErrorMessage(err,'The password could not be reset.'));}finally{setSaving(false);}};
  const setAccess=async(user:User)=>{try{setSaving(true);setError('');setMessage('');const response=await authApi.updateUserAccess(user.id,!user.active);setUsers((current)=>current.map((item)=>item.id===user.id?response.data:item));setMessage(`${user.name} is now ${response.data.active?'active':'suspended'}. Existing sessions were revoked.`);}catch(err){setError(getApiErrorMessage(err,'Account access could not be changed.'));}finally{setSaving(false);}};
  return <Panel title="Account administration" icon={<ShieldCheck className="h-5 w-5"/>}>
    <p className="mb-4 text-sm text-gray-600">Suspend access as soon as a user no longer requires the portal. Suspension and password reset revoke existing sessions and are retained in the audit history.</p>
    {error&&<p role="alert" className="mb-3 rounded bg-red-50 p-3 text-sm text-red-800">{error}</p>}{message&&<p role="status" className="mb-3 rounded bg-green-50 p-3 text-sm text-green-800">{message}</p>}
    <div className="mb-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-xs uppercase text-gray-500"><tr><th className="p-2">User</th><th className="p-2">Role</th><th className="p-2">Status</th><th className="p-2">Access</th></tr></thead><tbody>{users.map((item)=><tr key={item.id} className="border-t"><td className="p-2"><span className="block font-medium">{item.name}</span><span className="text-xs text-gray-500">{item.email}</span></td><td className="p-2">{item.role}</td><td className="p-2">{item.active?'Active':'Suspended'}</td><td className="p-2"><button type="button" disabled={saving||item.id===currentUserId} onClick={()=>setAccess(item)} className={`rounded px-3 py-1.5 text-xs font-semibold disabled:cursor-not-allowed disabled:opacity-40 ${item.active?'border border-red-300 text-red-700':'bg-green-700 text-white'}`}>{item.id===currentUserId?'Current account':item.active?'Suspend':'Reactivate'}</button></td></tr>)}</tbody></table></div>
    <form onSubmit={resetPassword} className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label className="text-sm font-medium">Recovery account<select required value={userId} onChange={(event)=>setUserId(event.target.value)} className="mt-1 w-full rounded border border-gray-300 px-3 py-2"><option value="">Select an account</option>{users.filter((item)=>item.active).map((item)=><option key={item.id} value={item.id}>{item.name} · {item.email} · {item.role}</option>)}</select></label><label className="text-sm font-medium">Temporary password<input required minLength={12} maxLength={128} type="password" autoComplete="new-password" value={password} onChange={(event)=>setPassword(event.target.value)} className="mt-1 w-full rounded border border-gray-300 px-3 py-2"/><span className="mt-1 block text-xs font-normal text-gray-500">12+ characters with uppercase, lowercase, number, and symbol.</span></label><button disabled={saving||!userId} className="self-start rounded bg-gray-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40 md:mt-6">{saving?'Updating…':'Reset password'}</button></form>
  </Panel>;
}

function SuggestionCard({item,working,act}:{item:AutomationSuggestion;working:string;act:(key:string,op:()=>Promise<unknown>,message:string)=>void}){const[comment,setComment]=useState('');let value:string;try{value=JSON.stringify(JSON.parse(item.suggestionJson),null,2);}catch{value=item.suggestionJson;}return <article className="rounded-lg border border-gray-200 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge value={item.type}/><span className="text-xs text-gray-500">{item.sourceEntityType} · {item.sourceEntityId.slice(0,8)}</span></div><h3 className="mt-2 font-semibold">{item.title}</h3><p className="mt-1 text-sm text-gray-600">{item.rationale}</p><pre className="mt-3 max-w-3xl overflow-x-auto rounded bg-gray-950 p-3 text-xs text-gray-100">{value}</pre></div><div className="min-w-[220px] space-y-2"><label className="block text-xs font-medium text-gray-700">Review note<input value={comment} onChange={(e)=>setComment(e.target.value)} className="mt-1 w-full rounded border border-gray-300 px-3 py-2 text-sm"/></label><div className="flex flex-wrap gap-2"><button disabled={!!working} onClick={()=>act(item.id,()=>automationApi.reviewSuggestion(item.id,{decision:'ACCEPT',comment}),'Suggestion accepted without changing its source record.')} className="rounded bg-green-700 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Accept</button><button disabled={!!working} onClick={()=>act(item.id,()=>automationApi.reviewSuggestion(item.id,{decision:'ACCEPT',comment,createWorkItem:true}),'Suggestion accepted and a traceable work item was created.')} className="rounded bg-blue-700 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">Accept & create task</button><button disabled={!!working} onClick={()=>act(item.id,()=>automationApi.reviewSuggestion(item.id,{decision:'REJECT',comment}),'Suggestion rejected and retained in the audit trail.')} className="rounded border border-red-300 px-3 py-2 text-xs font-semibold text-red-700 disabled:opacity-40">Reject</button></div></div></div></article>}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="mb-4 flex items-center gap-2 text-lg font-semibold text-gray-900">{icon}{title}</h2>{children}</section>}
function Metric({label,value,warn}:{label:string;value:number|string;warn?:boolean}){return <div className={`rounded-xl border p-4 ${warn?'border-red-200 bg-red-50':'border-gray-200 bg-white'}`}><p className="text-sm text-gray-600">{label}</p><p className="mt-1 text-3xl font-bold text-gray-900">{value}</p></div>}
function SmallMetric({label,value}:{label:string;value:number}){return <div className={`rounded-lg p-3 ${value?'bg-red-50 text-red-900':'bg-gray-50 text-gray-700'}`}><p className="text-xs">{label}</p><p className="text-2xl font-bold">{value}</p></div>}
function MetricRows({rows}:{rows:Array<[string,string|number]>}){return <dl className="space-y-2">{rows.map(([label,value])=><div key={label} className="flex items-center justify-between gap-4 border-b border-gray-100 py-2 last:border-0"><dt className="text-sm text-gray-600">{label}</dt><dd className="text-sm font-semibold text-gray-900">{value}</dd></div>)}</dl>}
function Badge({value}:{value:string}){return <span className={`inline-block rounded-full px-2.5 py-1 text-xs font-semibold ${tone(value)}`}>{pretty(value)}</span>}
function Empty({text}:{text:string}){return <p className="p-5 text-center text-sm text-gray-500">{text}</p>}
