import { FormEvent, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AlertCircle, ArrowLeft, Plus, Receipt, ShieldAlert, Store, Truck } from 'lucide-react';
import { getApiErrorMessage, procurementApi, toIsoDateTime } from '../api';
import { ProcurementRequest, ProcurementWorkspace as Workspace, Vendor } from '../types';
import { useAuth } from '../context/AuthContext';

const statusTone: Record<string, string> = { CLOSED: 'bg-green-100 text-green-800', MATCHED: 'bg-green-100 text-green-800', DELIVERED: 'bg-blue-100 text-blue-800', PARTIALLY_DELIVERED: 'bg-amber-100 text-amber-900', BACKORDERED: 'bg-red-100 text-red-800', BLOCKED: 'bg-red-100 text-red-800', AUTHORIZATION_REQUIRED: 'bg-violet-100 text-violet-800', ORDERED: 'bg-blue-100 text-blue-800', QUOTE_SELECTED: 'bg-cyan-100 text-cyan-800', QUOTING: 'bg-gray-100 text-gray-700', REQUESTED: 'bg-gray-100 text-gray-700' };

export default function ProcurementWorkspace() {
  const { projectId } = useParams<{ projectId: string }>();
  const { user } = useAuth();
  const internal = user?.role === 'ADMIN';
  const [data, setData] = useState<Workspace | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [showRequest, setShowRequest] = useState(false);
  const [showVendor, setShowVendor] = useState(false);
  const [requestForm, setRequestForm] = useState({ description: '', specification: '', quantity: '1', unit: 'EA', requiredBy: '', estimatedCost: '', costCode: '', required: true, clientVisible: false });
  const [vendorForm, setVendorForm] = useState({ name: '', contactName: '', email: '', phone: '', category: 'MATERIAL', complianceStatus: 'APPROVED' });

  const load = async () => {
    if (!projectId) return;
    try { setLoading(true); setError(''); setData((await procurementApi.getWorkspace(projectId)).data); }
    catch (err) { setError(getApiErrorMessage(err, 'The Procurement workspace could not be loaded.')); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, [projectId]);
  const mutate = async (operation: () => Promise<unknown>) => {
    try { setSaving(true); setError(''); await operation(); }
    catch (err) { setError(getApiErrorMessage(err, 'The Procurement change could not be saved.')); }
    finally { await load(); setSaving(false); }
  };
  const createRequest = (event: FormEvent) => { event.preventDefault(); mutate(async () => { await procurementApi.createRequest(projectId!, { ...requestForm, quantity: Number(requestForm.quantity), requiredBy: toIsoDateTime(requestForm.requiredBy), estimatedCostCents: requestForm.estimatedCost ? Math.round(Number(requestForm.estimatedCost) * 100) : null, costCode: requestForm.costCode || null, currencyCode: 'USD' }); setShowRequest(false); setRequestForm({ ...requestForm, description: '', specification: '', estimatedCost: '', costCode: '' }); }); };
  const createVendor = (event: FormEvent) => { event.preventDefault(); mutate(async () => { await procurementApi.createVendor({ ...vendorForm, contactName: vendorForm.contactName || null, email: vendorForm.email || null, phone: vendorForm.phone || null }); setShowVendor(false); setVendorForm({ ...vendorForm, name: '', contactName: '', email: '', phone: '' }); }); };

  if (loading) return <div className="flex min-h-64 items-center justify-center"><div className="h-9 w-9 animate-spin rounded-full border-4 border-cyan-200 border-t-cyan-700" /></div>;
  if (!data) return <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-red-800">{error || 'Procurement workspace unavailable.'}</div>;
  const exceptions = data.requests.filter((request) => ['BACKORDERED', 'BLOCKED', 'AUTHORIZATION_REQUIRED'].includes(request.status)).length;
  const ordered = data.requests.filter((request) => request.purchaseOrder).length;
  const delivered = data.requests.filter((request) => request.purchaseOrder?.deliveries.some((delivery) => delivery.inspectionStatus === 'PASSED')).length;

  return <div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><Link to={internal ? `/projects/${projectId}` : '/my-project'} className="text-sm text-blue-700"><ArrowLeft className="mr-1 inline h-4 w-4" />Back</Link><h1 className="mt-2 text-2xl font-bold text-gray-950">{data.client.name} · Procurement</h1><p className="mt-1 text-sm text-gray-600">Requests, competitive quotes, purchase authorization, delivery inspection, substitutions, and invoice verification.</p></div>{internal && <div className="flex gap-2"><button onClick={() => setShowVendor(!showVendor)} className="rounded-lg border border-cyan-300 bg-cyan-50 px-4 py-2 text-sm font-medium text-cyan-900"><Store className="mr-1 inline h-4 w-4" />Vendor</button><button onClick={() => setShowRequest(!showRequest)} className="rounded-lg bg-cyan-700 px-4 py-2 text-sm font-medium text-white"><Plus className="mr-1 inline h-4 w-4" />Request</button></div>}</header>
    {error && <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertCircle className="mr-2 inline h-4 w-4" />{error}</div>}
    <section className="grid gap-4 md:grid-cols-4"><Metric label="Requests" value={data.requests.length} /><Metric label="Purchase orders" value={ordered} /><Metric label="Received" value={delivered} /><Metric label="Exceptions" value={exceptions} alert={exceptions > 0} /></section>
    {internal && <section className={`rounded-xl border p-5 ${data.blockers.length ? 'border-red-200 bg-red-50' : 'border-green-200 bg-green-50'}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="font-semibold"><ShieldAlert className="mr-2 inline h-5 w-5" />Procurement → Field Execution handoff</h2><p className="mt-1 text-sm">{data.blockers.length ? `${data.blockers.length} unresolved verification condition${data.blockers.length === 1 ? '' : 's'}.` : 'All required procurement requests are verified and closed.'}</p>{data.blockers.length > 0 && <ul className="mt-2 list-disc space-y-1 pl-5 text-xs">{data.blockers.slice(0, 8).map((blocker) => <li key={`${blocker.type}-${blocker.id}`}>{blocker.title}</li>)}</ul>}</div><button disabled={saving || data.blockers.length > 0 || data.project.currentLifecycleStage !== 'PROCUREMENT'} onClick={() => mutate(() => procurementApi.approveGate(projectId!))} className="rounded-lg bg-green-700 px-4 py-2 text-sm font-medium text-white disabled:bg-gray-300">Approve handoff</button></div></section>}
    {showVendor && <form onSubmit={createVendor} className="grid gap-3 rounded-xl border border-cyan-200 bg-cyan-50 p-5 md:grid-cols-3"><h2 className="md:col-span-3 font-semibold">Add approved vendor or subcontractor</h2><Field label="Vendor name" value={vendorForm.name} set={(value) => setVendorForm({ ...vendorForm, name: value })} required /><Field label="Contact" value={vendorForm.contactName} set={(value) => setVendorForm({ ...vendorForm, contactName: value })} /><Field label="Email" type="email" value={vendorForm.email} set={(value) => setVendorForm({ ...vendorForm, email: value })} /><Field label="Phone" value={vendorForm.phone} set={(value) => setVendorForm({ ...vendorForm, phone: value })} /><Field label="Category" value={vendorForm.category} set={(value) => setVendorForm({ ...vendorForm, category: value })} /><Select label="Compliance" value={vendorForm.complianceStatus} set={(value) => setVendorForm({ ...vendorForm, complianceStatus: value })} options={['APPROVED', 'PENDING', 'SUSPENDED', 'EXPIRED']} /><button className="rounded-lg bg-cyan-700 px-4 py-2 text-sm text-white">Save vendor</button></form>}
    {showRequest && <form onSubmit={createRequest} className="grid gap-3 rounded-xl border border-cyan-200 bg-cyan-50 p-5 md:grid-cols-3"><h2 className="md:col-span-3 font-semibold">New material or service request</h2><Field label="Description" value={requestForm.description} set={(value) => setRequestForm({ ...requestForm, description: value })} required /><Field label="Specification" value={requestForm.specification} set={(value) => setRequestForm({ ...requestForm, specification: value })} required /><Field label="Quantity" type="number" value={requestForm.quantity} set={(value) => setRequestForm({ ...requestForm, quantity: value })} required /><Field label="Unit" value={requestForm.unit} set={(value) => setRequestForm({ ...requestForm, unit: value })} required /><Field label="Required by" type="datetime-local" value={requestForm.requiredBy} set={(value) => setRequestForm({ ...requestForm, requiredBy: value })} required /><Field label="Estimated cost" type="number" value={requestForm.estimatedCost} set={(value) => setRequestForm({ ...requestForm, estimatedCost: value })} /><Field label="Cost code" value={requestForm.costCode} set={(value) => setRequestForm({ ...requestForm, costCode: value })} /><div className="flex items-center gap-4"><Check label="Required" checked={requestForm.required} set={(value) => setRequestForm({ ...requestForm, required: value })} /><Check label="Client visible" checked={requestForm.clientVisible} set={(value) => setRequestForm({ ...requestForm, clientVisible: value })} /></div><button className="rounded-lg bg-cyan-700 px-4 py-2 text-sm text-white">Create request</button></form>}
    {internal && <section className="rounded-xl border border-gray-200 bg-white p-5"><h2 className="font-semibold"><Store className="mr-2 inline h-5 w-5 text-cyan-700" />Vendor directory</h2><div className="mt-3 flex flex-wrap gap-2">{data.vendors.map((vendor) => <span key={vendor.id} className="rounded-full bg-gray-100 px-3 py-1.5 text-xs">{vendor.name} · {pretty(vendor.category)} · {vendor.complianceStatus}</span>)}{!data.vendors.length && <span className="text-sm text-gray-500">No active vendors.</span>}</div></section>}
    <section className="space-y-5">{data.requests.map((request) => <RequestCard key={request.id} request={request} vendors={data.vendors} internal={internal} saving={saving} mutate={mutate} />)}{!data.requests.length && <div className="rounded-xl border border-dashed border-gray-300 bg-white p-10 text-center text-sm text-gray-500">No procurement requests yet.</div>}</section>
  </div>;
}

function RequestCard({ request, vendors, internal, saving, mutate }: { request: ProcurementRequest; vendors: Vendor[]; internal: boolean; saving: boolean; mutate: (operation: () => Promise<unknown>) => void }) {
  const [quote, setQuote] = useState({ vendorId: '', amount: '', tax: '', scope: '', validUntil: '', leadTimeDays: '' });
  const [poNumber, setPoNumber] = useState('');
  const [delivery, setDelivery] = useState({ quantityReceived: '', condition: 'GOOD', receivedAt: '' });
  const [substitution, setSubstitution] = useState({ proposedSpecification: '', reason: '', costImpact: '0', scheduleImpactDays: '0', clientAuthorizationRequired: false });
  const [invoice, setInvoice] = useState({ invoiceReference: '', deliveredAmount: '', invoicedAmount: '' });
  const [open, setOpen] = useState('');
  const money = (cents: number) => new Intl.NumberFormat(undefined, { style: 'currency', currency: request.currencyCode }).format(cents / 100);
  const addQuote = () => mutate(() => procurementApi.addQuote(request.id, { vendorId: quote.vendorId, amountCents: Math.round(Number(quote.amount) * 100), taxCents: Math.round(Number(quote.tax || 0) * 100), scope: quote.scope, validUntil: toIsoDateTime(quote.validUntil), leadTimeDays: quote.leadTimeDays ? Number(quote.leadTimeDays) : null, currencyCode: request.currencyCode }));
  const po = request.purchaseOrder;
  return <article className="rounded-xl border border-gray-200 bg-white p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusTone[request.status] || 'bg-gray-100 text-gray-700'}`}>{pretty(request.status)}</span>{request.required && <span className="text-xs font-medium text-gray-500">Required</span>}{request.clientVisible && <span className="text-xs text-blue-700">Client visible</span>}</div><h2 className="mt-3 font-semibold">{request.description}</h2><p className="mt-1 text-sm text-gray-600">{request.specification}</p><div className="mt-2 flex flex-wrap gap-x-4 text-xs text-gray-500"><span>{request.quantity} {request.unit}</span><span>Required {new Date(request.requiredBy).toLocaleString()}</span>{request.costCode && <span>Cost code {request.costCode}</span>}{request.estimatedCostCents != null && <span>Estimate {money(request.estimatedCostCents)}</span>}</div></div>{internal && <div className="flex flex-wrap gap-2">{!po && <button onClick={() => setOpen(open === 'quote' ? '' : 'quote')} className="rounded border px-3 py-2 text-xs">Add quote</button>}{request.selectedQuote && !po && <button onClick={() => setOpen(open === 'po' ? '' : 'po')} className="rounded bg-blue-700 px-3 py-2 text-xs text-white">Issue PO</button>}{po && <button onClick={() => setOpen(open === 'delivery' ? '' : 'delivery')} className="rounded border px-3 py-2 text-xs"><Truck className="mr-1 inline h-4 w-4" />Receive</button>}<button onClick={() => setOpen(open === 'substitution' ? '' : 'substitution')} className="rounded border px-3 py-2 text-xs">Substitution</button>{po && <button onClick={() => setOpen(open === 'invoice' ? '' : 'invoice')} className="rounded border px-3 py-2 text-xs"><Receipt className="mr-1 inline h-4 w-4" />Invoice match</button>}<button onClick={() => mutate(() => procurementApi.markBackorder(request.id))} className="rounded bg-red-50 px-3 py-2 text-xs text-red-800">Backorder</button>{request.status !== 'CLOSED' && <button onClick={() => mutate(() => procurementApi.closeRequest(request.id))} className="rounded bg-green-700 px-3 py-2 text-xs text-white">Close</button>}</div>}</div>
    {internal && open === 'po' && request.selectedQuote && !po && <div className="mt-4 grid gap-2 rounded-lg border border-blue-200 bg-blue-50 p-4 md:grid-cols-3"><Field label="Purchase order number" value={poNumber} set={setPoNumber} required /><div className="flex items-end"><button disabled={saving || poNumber.trim().length < 2} onClick={() => mutate(() => procurementApi.createPurchaseOrder(request.id, poNumber.trim()))} className="rounded bg-blue-700 px-3 py-2 text-xs text-white disabled:opacity-50">Create purchase order</button></div></div>}
    {internal && open === 'quote' && <div className="mt-4 grid gap-2 rounded-lg border p-4 md:grid-cols-3"><Select label="Approved vendor" value={quote.vendorId} set={(value) => setQuote({ ...quote, vendorId: value })} options={vendors.filter((vendor) => vendor.complianceStatus === 'APPROVED').map((vendor) => vendor.id)} labels={Object.fromEntries(vendors.map((vendor) => [vendor.id, vendor.name]))} empty="Choose vendor" /><Field label="Subtotal" type="number" value={quote.amount} set={(value) => setQuote({ ...quote, amount: value })} /><Field label="Tax" type="number" value={quote.tax} set={(value) => setQuote({ ...quote, tax: value })} /><Field label="Scope" value={quote.scope} set={(value) => setQuote({ ...quote, scope: value })} /><Field label="Valid until" type="datetime-local" value={quote.validUntil} set={(value) => setQuote({ ...quote, validUntil: value })} /><Field label="Lead-time days" type="number" value={quote.leadTimeDays} set={(value) => setQuote({ ...quote, leadTimeDays: value })} /><button disabled={!quote.vendorId || !quote.amount || quote.scope.length < 3} onClick={addQuote} className="rounded bg-cyan-700 px-3 py-2 text-xs text-white disabled:opacity-40">Save quote</button></div>}
    {request.quotes && request.quotes.length > 0 && <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase text-gray-500"><tr><th className="p-2">Vendor</th><th className="p-2">Scope</th><th className="p-2">Lead time</th><th className="p-2">Total</th>{internal && <th className="p-2">Action</th>}</tr></thead><tbody>{request.quotes.map((item) => <tr key={item.id} className={item.id === request.selectedQuoteId ? 'bg-cyan-50' : 'border-t'}><td className="p-2 font-medium">{item.vendor.name}</td><td className="p-2">{item.scope}</td><td className="p-2">{item.leadTimeDays == null ? '—' : `${item.leadTimeDays} days`}</td><td className="p-2">{money(item.totalCents)}</td>{internal && <td className="p-2">{item.id === request.selectedQuoteId ? 'Selected' : <button onClick={() => mutate(() => procurementApi.selectQuote(request.id, item.id))} className="text-xs font-medium text-cyan-800">Select</button>}</td>}</tr>)}</tbody></table></div>}
    {po && <section className="mt-4 rounded-lg bg-gray-50 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="text-sm font-semibold">PO {po.orderNumber} · {po.vendor.name}</h3><span className="text-sm font-medium">{money(po.approvedAmountCents)}</span></div><div className="mt-3 space-y-2">{po.deliveries.map((item) => <div key={item.id} className="flex flex-col justify-between gap-2 rounded bg-white p-3 text-xs sm:flex-row sm:items-center"><span>{item.quantityReceived} {request.unit} · {item.condition} · Inspection {item.inspectionStatus}</span>{internal && item.inspectionStatus === 'PENDING' && <span className="flex gap-2"><button onClick={() => mutate(() => procurementApi.inspectDelivery(item.id, true))} className="text-green-700">Pass</button><button onClick={() => mutate(() => procurementApi.inspectDelivery(item.id, false, 'Inspection failed; review required.'))} className="text-red-700">Fail</button></span>}</div>)}</div>{po.invoiceMatches.map((match) => <div key={match.id} className={`mt-2 rounded p-3 text-xs ${match.status === 'MATCHED' ? 'bg-green-100 text-green-900' : 'bg-red-100 text-red-900'}`}>{match.invoiceReference} · Ordered {money(match.orderedAmountCents)} · Delivered {money(match.deliveredAmountCents)} · Invoiced {money(match.invoicedAmountCents)} · Variance {money(match.varianceAmountCents)} · {match.status}</div>)}</section>}
    {internal && open === 'delivery' && po && <div className="mt-4 grid gap-2 rounded-lg border p-4 md:grid-cols-3"><Field label="Quantity received" type="number" value={delivery.quantityReceived} set={(value) => setDelivery({ ...delivery, quantityReceived: value })} /><Select label="Condition" value={delivery.condition} set={(value) => setDelivery({ ...delivery, condition: value })} options={['GOOD', 'DAMAGED', 'INCOMPLETE', 'REJECTED']} /><Field label="Received at" type="datetime-local" value={delivery.receivedAt} set={(value) => setDelivery({ ...delivery, receivedAt: value })} /><button disabled={!delivery.quantityReceived} onClick={() => mutate(() => procurementApi.recordDelivery(po.id, { quantityReceived: Number(delivery.quantityReceived), condition: delivery.condition, receivedAt: toIsoDateTime(delivery.receivedAt) || new Date().toISOString() }))} className="rounded bg-cyan-700 px-3 py-2 text-xs text-white">Record delivery</button></div>}
    {internal && open === 'substitution' && <div className="mt-4 grid gap-2 rounded-lg border p-4 md:grid-cols-3"><Field label="Proposed specification" value={substitution.proposedSpecification} set={(value) => setSubstitution({ ...substitution, proposedSpecification: value })} /><Field label="Reason" value={substitution.reason} set={(value) => setSubstitution({ ...substitution, reason: value })} /><Field label="Cost impact" type="number" value={substitution.costImpact} set={(value) => setSubstitution({ ...substitution, costImpact: value })} /><Field label="Schedule days" type="number" value={substitution.scheduleImpactDays} set={(value) => setSubstitution({ ...substitution, scheduleImpactDays: value })} /><Check label="Client authorization required" checked={substitution.clientAuthorizationRequired} set={(value) => setSubstitution({ ...substitution, clientAuthorizationRequired: value })} /><button disabled={substitution.proposedSpecification.length < 3 || substitution.reason.length < 10} onClick={() => mutate(() => procurementApi.createSubstitution(request.id, { ...substitution, costImpactCents: Math.round(Number(substitution.costImpact) * 100), scheduleImpactDays: Number(substitution.scheduleImpactDays), currencyCode: request.currencyCode }))} className="rounded bg-violet-700 px-3 py-2 text-xs text-white disabled:opacity-40">Request substitution</button></div>}
    {internal && open === 'invoice' && po && <div className="mt-4 grid gap-2 rounded-lg border p-4 md:grid-cols-3"><Field label="Invoice reference" value={invoice.invoiceReference} set={(value) => setInvoice({ ...invoice, invoiceReference: value })} /><Field label="Delivered value" type="number" value={invoice.deliveredAmount} set={(value) => setInvoice({ ...invoice, deliveredAmount: value })} /><Field label="Invoiced value" type="number" value={invoice.invoicedAmount} set={(value) => setInvoice({ ...invoice, invoicedAmount: value })} /><button disabled={!invoice.invoiceReference || !invoice.deliveredAmount || !invoice.invoicedAmount} onClick={() => mutate(() => procurementApi.invoiceMatch(request.id, { invoiceReference: invoice.invoiceReference, deliveredAmountCents: Math.round(Number(invoice.deliveredAmount) * 100), invoicedAmountCents: Math.round(Number(invoice.invoicedAmount) * 100) }))} className="rounded bg-gray-900 px-3 py-2 text-xs text-white">Run three-way match</button></div>}
  </article>;
}

function Metric({ label, value, alert }: { label: string; value: number; alert?: boolean }) { return <div className={`rounded-xl border p-4 ${alert ? 'border-red-200 bg-red-50 text-red-900' : 'border-gray-200 bg-white text-gray-900'}`}><p className="text-sm font-medium">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div>; }
function Field({ label, value, set, type = 'text', required }: { label: string; value: string; set: (value: string) => void; type?: string; required?: boolean }) { return <label className="text-sm font-medium">{label}<input required={required} type={type} value={value} onChange={(event) => set(event.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2" /></label>; }
function Select({ label, value, set, options, labels = {}, empty }: { label: string; value: string; set: (value: string) => void; options: string[]; labels?: Record<string, string>; empty?: string }) { return <label className="text-sm font-medium">{label}<select value={value} onChange={(event) => set(event.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 bg-white px-3 py-2">{empty && <option value="">{empty}</option>}{options.map((option) => <option key={option} value={option}>{labels[option] || pretty(option)}</option>)}</select></label>; }
function Check({ label, checked, set }: { label: string; checked: boolean; set: (value: boolean) => void }) { return <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={checked} onChange={(event) => set(event.target.checked)} />{label}</label>; }
function pretty(value: string) { return value.replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
